name: CI

on:
  push:
    branches: [main, feature/*]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest matplotlib scikit-learn
    
    - name: Run leakage guard test
      run: |
        python -m pytest tests/test_leakage_guard.py -v
    
    - name: Run basic unit tests
      run: |
        python -m pytest tests/ -v --ignore=tests/test_leakage_guard.py || true
    
    - name: Check for linter errors (optional)
      run: |
        pip install ruff || true
        ruff check graph_qa/ scripts/ || true

